import SKILL_DOMAIN from './SKILL_DOMAIN.js'

const SKILL_DOMAIN_PREFIX = {
  [SKILL_DOMAIN.CORE]: 'hc',
  [SKILL_DOMAIN.BACKEND]: 'hb',
  [SKILL_DOMAIN.FRONTEND]: 'hf',
  [SKILL_DOMAIN.SUPPORT]: 'hs',
}

export default SKILL_DOMAIN_PREFIX
